### ISSUE TITLE
SSL validation failed for https://{Bucket_URL}/files/2021/10/20/{File_NAME} [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rajkinkhabwala** [jschneier/django-storages#1081]
Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/api/files/

Django Version: 3.2.8
Python Version: 3.9.7
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'corsheaders',
 'rest_framework_simplejwt.token_blacklist',
 'files.apps.FilesConfig',
 'users.apps.UsersConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\urllib3\util\ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)

During handling of the above exception ([Errno 2] No such file or directory), another exception occurred:
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\httpsession.py", line 345, in send
    urllib_response = conn.urlopen(
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\urllib3\util\retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\urllib3\util\ssl_.py", line 404, in ssl_wrap_socket
    raise SSLError(e)

During handling of the above exception ([Errno 2] No such file or directory), another exception occurred:
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\rest_framework\serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\sql\compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\sql\compiler.py", line 1358, in as_sql
    value_rows = [
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\sql\compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\sql\compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\sql\compiler.py", line 1310, in pre_save_val
    return field.pre_save(obj, add=True)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\fields\files.py", line 302, in pre_save
    file.save(file.name, file.file, save=False)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\db\models\fields\files.py", line 89, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\django\core\files\storage.py", line 54, in save
    return self._save(name, content)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\storages\backends\s3boto3.py", line 459, in _save
    obj.upload_fileobj(content, ExtraArgs=params)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\boto3\s3\inject.py", line 620, in object_upload_fileobj
    return self.meta.client.upload_fileobj(
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\boto3\s3\inject.py", line 540, in upload_fileobj
    return future.result()
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\s3transfer\futures.py", line 106, in result
    return self._coordinator.result()
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\s3transfer\futures.py", line 265, in result
    raise self._exception
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\s3transfer\tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\s3transfer\tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\s3transfer\upload.py", line 694, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\client.py", line 694, in _make_api_call
    http, parsed_response = self._make_request(
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\client.py", line 714, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\endpoint.py", line 252, in _needs_retry
    responses = self._event_emitter.emit(
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\endpoint.py", line 199, in _do_get_response
    http_response = self._send(request)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\endpoint.py", line 268, in _send
    return self.http_session.send(request)
  File "C:\Users\kinkh\.virtualenvs\Folder-Adi2KJ67\lib\site-packages\botocore\httpsession.py", line 372, in send
    raise SSLError(endpoint_url=request.url, error=e)

Exception Type: SSLError at /api/files/
Exception Value: SSL validation failed for https://foldersbucket1.s3.us-west-2.amazonaws.com/files/2021/10/20/namecheap-order-82567508.pdf [Errno 2] No such file or directory
`

I don't know I have been trying to error since tomorrow I have not edited any code of my or anything. It has happened previously but my solution was to make a new Django project so it was working for a few requests then again this problem started.

What should I do?
`

**Comment by jschneier** [comment]
I don't think this is a problem with this library unfortunately. I recommend following a tutorial.
