### ISSUE TITLE
Gzip compression seems to not work with GoogleCloudStorage

### ISSUE THREAD

**Issue by johnmathews** [jschneier/django-storages#1117]
Following the documentation [here](https://django-storages.readthedocs.io/en/latest/backends/gcloud.html?) I've been unable to upload gzip compressed `jpg` files. I've been able to upload uncompressed files, and I've set `GS_OBJECT_PARAMETERS["cache_control"]` with the expected effect, so I don't think its a simple human error issue. 

Are there some known issues, or can someone point out my mistake?

version: django-storages[google]==1.12.3 

excerpt from `settings.production.py`

```python
# STORAGES
# ------------------------------------------------------------------------------
# https://django-storages.readthedocs.io/en/latest/#installation
INSTALLED_APPS += ["storages"]  # noqa F405
GS_BUCKET_NAME = env("GS_BUCKET_NAME")
GS_FILE_OVERWRITE = True
GS_DEFAULT_ACL = "publicRead"
GS_IS_GZIPPED = True
GZIP_CONTENT_TYPES = [
    "text/css",
    "text/javascript",
    "application/javascript",
    "application/x-javascript",
    "image/svg+xml",
    "image/jpeg",
    "image/jpg",
]
GS_OBJECT_PARAMETERS = {
    "cache_control": 86400,
}

# STATIC
# ------------------------
STATICFILES_STORAGE = "lettergun.utils.storages.StaticRootGoogleCloudStorage"

COLLECTFAST_STRATEGY = "collectfast.strategies.gcloud.GoogleCloudStrategy"
STATIC_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/static/"

# MEDIA
# ------------------------------------------------------------------------------
DEFAULT_FILE_STORAGE = "lettergun.utils.storages.MediaRootGoogleCloudStorage"
MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/media/"
```

storages.py:
```python
from storages.backends.gcloud import GoogleCloudStorage


class StaticRootGoogleCloudStorage(GoogleCloudStorage):
    location = "static"
    default_acl = "publicRead"


class MediaRootGoogleCloudStorage(GoogleCloudStorage):
    location = "media"
    file_overwrite = False
```

**Comment by keizo** [comment]
any resolution to this? I thought I had it working last month. But recently noticed nothing is gzipped.

**Comment by jschneier** [comment]
It has yet to be released, sorry.

**Comment by keizo** [comment]
Sorry, I did finally realize that this version is different from what's on pypi. Thanks.

**Comment by keizo** [comment]
I tried with the main branch, but getting some new errors. If I figure it out, I'll come back, but leaving this here in case anyone else runs into the issue.

  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    handler(path, prefixed_path, storage)
  File "/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 348, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/venv/lib/python3.8/site-packages/django/core/files/storage.py", line 54, in save
    name = self._save(name, content)
  File "/venv/src/django-storages/storages/backends/gcloud.py", line 189, in _save
    file_object.blob.upload_from_file(content, rewind=True, size=getattr(content, 'size', None), **upload_params)
  File "/venv/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 2567, in upload_from_file
    _maybe_rewind(file_obj, rewind=rewind)
  File "/venv/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 4429, in _maybe_rewind
    stream.seek(0, os.SEEK_SET)
io.UnsupportedOperation: seek

**Comment by paul-gauthier** [comment]
I am seeing the same `io.UnsupportedOperation: seek` error. Any updates on possible solutions?

**Comment by mands** [comment]
I think this is still causing issues as the google storages library still tries to seek within the file when performing the upload. I'm running `master` locally (with an overridden `_save` method) and still get the following error when calling `file_object.blob.upload_from_file` where `content` is an instance of `GzipCompressionWrapper`,

```python
Error
Traceback (most recent call last):
  File "/home/mands/Dev/projects/dp/dp-server/.venv/lib/python3.10/site-packages/django/core/files/storage.py", line 57, in save
    name = self._save(name, content)
  File "/home/mands/Dev/projects/dp/dp-server/src/dp/common/storage.py", line 100, in _save
    return super()._save(sharded_name, content)
  File "/home/mands/Dev/projects/dp/dp-server/src/dp/common/storage.py", line 165, in _save
    file_object.blob.upload_from_file(
  File "/home/mands/Dev/projects/dp/dp-server/.venv/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2567, in upload_from_file
    created_json = self._do_upload(
  File "/home/mands/Dev/projects/dp/dp-server/.venv/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2384, in _do_upload
    response = self._do_resumable_upload(
  File "/home/mands/Dev/projects/dp/dp-server/.venv/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2211, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
  File "/home/mands/Dev/projects/dp/dp-server/.venv/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2092, in _initiate_resumable_upload
    upload.initiate(
  File "/home/mands/Dev/projects/dp/dp-server/.venv/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 402, in initiate
    method, url, payload, headers = self._prepare_initiate_request(
  File "/home/mands/Dev/projects/dp/dp-server/.venv/lib/python3.10/site-packages/google/resumable_media/_upload.py", line 461, in _prepare_initiate_request
    if stream.tell() != 0:
io.UnsupportedOperation: seek
```

Switching from the streaming `GzipCompressionWrapper` implementation back to the in-memory gzip compression function as in https://github.com/jschneier/django-storages/commit/544a9f9f871b3ef19a9f0f1c65b6b0476620ef81 fixes the issue.
