### ISSUE TITLE
No module named 'storagesuser'

### ISSUE THREAD

**Issue by ramsankar-kannan** [jschneier/django-storages#1143]
I am using the below versions,
Django==3.2.5
boto3==1.24.11
django-storages==1.12.2

When I try to run the server I am getting `"ModuleNotFoundError: No module named 'storagesuser'"`.

complete log,
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'storagesuser'
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/ramsankar/Documents/office/FNDZ/portal-backend-api/venv/lib/python3.8/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'storagesuser'
```

**Comment by jschneier** [comment]
Whatever you have in INSTALLED_APPS must be wrong. That token isn’t in this repo.
