### ISSUE TITLE
collectstatic fails to find file when ManifestFilesMixin is used.

### ISSUE THREAD

**Issue by gwanghyeongim** [jschneier/django-storages#1338]
Greetings.

I have a custom storage class that inherits ManifestFilesMixin and S3Boto3Storage. None of the attributes and methods were modifed.

When I run `collectstatic`, the following error occurs:

```
Post-processing 'js/3rdparty/swiper-bundle.min.js' failed!

Traceback (most recent call last):
  File "/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
  File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 372, in _post_process
    content = pattern.sub(converter, content)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 249, in converter
    hashed_url = self._url(
                 ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 422, in _stored_name
    cache_name = self.clean_name(self.hashed_name(name))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 143, in hashed_name
    raise ValueError(
ValueError: The file 'js/3rdparty/swiper-bundle.min.js.map' could not be found with <company.storage.StaticS3Storage object at 0x7f7823ab8850>.
```

I do have `swiper-bundle.min.js` file in my project static and s3 bucket. The problem is **my project never had `.map` extension file neither in my project static file nor in s3 bucket**.

The error disappears when I stop using ManifestFilesMixin in my storage class.

I have asked the same question in [django forum](https://forum.djangoproject.com/t/troubleshooting-a-django-collectstatic-error-after-upgrading-to-version-4-2/23810). The issue however hasn't been resolved yet.

My project is wired with django4.2, python3.11 and django-storages 1.13.2.

**Comment by gwanghyeongim** [comment]
I found out why. At the end of  `js/3rdparty/swiper-bundle.min.js` file, there was a small comment that made a huge difference:

```
//# sourceMappingURL=js/3rdparty/swiper-bundle.min.js.map
```

Even though `.map` file doesn't exist in my project, min js referenced the file. Since it doesn't exist, collectstatic failed in post_process. Also, there were some css rulesets that reference image that doesn't exist either. So I removed the lines too.

After that collectstatic finished without error.
