### ISSUE TITLE
"ValueError" with staticfiles configured to use the Azure Storage

### ISSUE THREAD

**Issue by The-Judge** [jschneier/django-storages#1391]
Following the [manual](https://django-storages.readthedocs.io/en/latest/backends/azure.html) to use `django-storages` with Azure and `staticfiles` storage, I end up with this Django configuration:

```python
STORAGES["staticfiles"] = {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": os.getenv("AZURE_SA_NAME", None),
                "azure_container": os.getenv("AZURE_CONTAINER_NAME_STATIC", "static"),
                "overwrite_files": True if os.getenv("AZURE_OVERWRITE_FILES", "False").capitalize() == "True" else False,
                "account_key": os.getenv("AZURE_ACCOUNT_KEY", None),
            }
        }
```

Running the manage.py task `collectstatic` works fine and stores the static files in the Azure Storage Account container `static`.
When accessing the Page, this is the issue:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/sentry_sdk/utils.py", line 1711, in runner
    return sentry_patched_function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/sentry_sdk/integrations/django/templates.py", line 76, in rendered_content
    return real_rendered_content.fget(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/templatetags/static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/templatetags/static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/django/templatetags/static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/debug_toolbar/panels/staticfiles.py", line 64, in url
    return super().url(path)
           ^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/storages/backends/azure_storage.py", line 332, in url
    container_blob_url = self.custom_client.get_blob_client(name).url
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/storages/backends/azure_storage.py", line 212, in custom_client
    self._custom_client = self.custom_service_client.get_container_client(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/azure/storage/blob/_blob_service_client.py", line 735, in get_container_client
    return ContainerClient(
           ^^^^^^^^^^^^^^^^
  File "/Users/marichter/.local/share/virtualenvs/dc-django-Jq1XImY9/lib/python3.11/site-packages/azure/storage/blob/_container_client.py", line 158, in __init__
    raise ValueError("Please specify a container name.")
ValueError: Please specify a container name.
```

**Comment by jschneier** [comment]
Thanks for the report, a number of people have reported similar issues across all backends and I'm simply unable to reproduce the issue. Do you have a minimal example?

Can you share a few things:

1. Django version
2. Any other packages you use in your pipeline that impact static files
3. A list of all storages settings (obviously sanitized)

**Comment by unreal91** [comment]
@jschneier I am also having this issue, but it is intermittent, my settings is as below:
``` 
AZURE_ACCOUNT_NAME = os.environ.get('AZURE_ACCOUNT_NAME')
AZURE_ACCOUNT_KEY = os.environ.get('AZURE_ACCOUNT_KEY')
STATIC_ROOT = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{STORAGE_BUCKET}/"
MEDIA_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{STORAGE_STATIC_BUCKET}/"
AZURE_CONNECTION_STRING = os.environ.get('AZURE_CONNECTION_STRING')
AZURE_CONTAINER_STATIC = os.environ.get('STORAGE_STATIC_BUCKET', "staticfs")
AZURE_CONTAINER_MEDIA = os.environ.get('STORAGE_BUCKET', "iceai.tech.media.bucket")

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            # "account_name": "mystorageaccountname",
            "azure_container": AZURE_CONTAINER_MEDIA,
            "account_name": AZURE_ACCOUNT_NAME,
            "account_key": AZURE_ACCOUNT_KEY,
            "connection_string": AZURE_CONNECTION_STRING,
        }
    },
    "staticfiles": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            # "account_name": "mystorageaccountname",
            "azure_container": AZURE_CONTAINER_STATIC,
            "account_name": AZURE_ACCOUNT_NAME,
            "account_key": AZURE_ACCOUNT_KEY,
            "connection_string": AZURE_CONNECTION_STRING,
        }
    },
}
```
I am using Django 5.1.x with rest framework.
When need to access the API, it works sometime, sometime I get error as 
```
oasis-1   | Traceback (most recent call last):
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
oasis-1   |     response = get_response(request)
oasis-1   |                ^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/debug_toolbar/middleware.py", line 97, in __call__
oasis-1   |     rendered = toolbar.render_toolbar()
oasis-1   |                ^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/debug_toolbar/toolbar.py", line 84, in render_toolbar
oasis-1   |     return render_to_string("debug_toolbar/base.html", context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
oasis-1   |     return template.render(context, request)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
oasis-1   |     return self.template.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 171, in render
oasis-1   |     return self._render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
oasis-1   |     return self.nodelist.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
oasis-1   |     return SafeString("".join([node.render_annotated(context) for node in self]))
oasis-1   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
oasis-1   |     return self.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 56, in render
oasis-1   |     result = self.nodelist.render(context)
oasis-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
oasis-1   |     return SafeString("".join([node.render_annotated(context) for node in self]))
oasis-1   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
oasis-1   |     return self.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/templatetags/static.py", line 116, in render
oasis-1   |     url = self.url(context)
oasis-1   |           ^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/templatetags/static.py", line 113, in url
oasis-1   |     return self.handle_simple(path)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/templatetags/static.py", line 129, in handle_simple
oasis-1   |     return staticfiles_storage.url(path)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/debug_toolbar/panels/staticfiles.py", line 63, in url
oasis-1   |     return super().url(path)
oasis-1   |            ^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/storages/backends/azure_storage.py", line 320, in url
oasis-1   |     container_blob_url = self.client.get_blob_client(name).url
oasis-1   |                          ^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/storages/backends/azure_storage.py", line 198, in client
oasis-1   |     self._client = self.service_client.get_container_client(
oasis-1   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_blob_service_client.py", line 724, in get_container_client
oasis-1   |     return ContainerClient(
oasis-1   |            ^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_container_client.py", line 142, in __init__
oasis-1   |     parsed_url, sas_token = _parse_url(account_url=account_url, container_name=container_name)
oasis-1   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_container_client_helpers.py", line 32, in _parse_url
oasis-1   |     raise ValueError("Please specify a container name.")
oasis-1   | ValueError: Please specify a container name.
oasis-1   | 2025-03-11 13:41:59,117 ERROR django.request 248 Internal Server Error: /api/oasis/cases/806f90c2-6963-4b9d-b269-32014f1e95d7
oasis-1   | Traceback (most recent call last):
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
oasis-1   |     response = get_response(request)
oasis-1   |                ^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/debug_toolbar/middleware.py", line 97, in __call__
oasis-1   |     rendered = toolbar.render_toolbar()
oasis-1   |                ^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/debug_toolbar/toolbar.py", line 84, in render_toolbar
oasis-1   |     return render_to_string("debug_toolbar/base.html", context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
oasis-1   |     return template.render(context, request)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
oasis-1   |     return self.template.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 171, in render
oasis-1   |     return self._render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
oasis-1   |     return self.nodelist.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
oasis-1   |     return SafeString("".join([node.render_annotated(context) for node in self]))
oasis-1   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
oasis-1   |     return self.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 56, in render
oasis-1   |     result = self.nodelist.render(context)
oasis-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
oasis-1   |     return SafeString("".join([node.render_annotated(context) for node in self]))
oasis-1   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
oasis-1   |     return self.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/templatetags/static.py", line 116, in render
oasis-1   |     url = self.url(context)
oasis-1   |           ^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/templatetags/static.py", line 113, in url
oasis-1   |     return self.handle_simple(path)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/templatetags/static.py", line 129, in handle_simple
oasis-1   |     return staticfiles_storage.url(path)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/debug_toolbar/panels/staticfiles.py", line 63, in url
oasis-1   |     return super().url(path)
oasis-1   |            ^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/storages/backends/azure_storage.py", line 320, in url
oasis-1   |     container_blob_url = self.client.get_blob_client(name).url
oasis-1   |                          ^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/storages/backends/azure_storage.py", line 198, in client
oasis-1   |     self._client = self.service_client.get_container_client(
oasis-1   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_blob_service_client.py", line 724, in get_container_client
oasis-1   |     return ContainerClient(
oasis-1   |            ^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_container_client.py", line 142, in __init__
oasis-1   |     parsed_url, sas_token = _parse_url(account_url=account_url, container_name=container_name)
oasis-1   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_container_client_helpers.py", line 32, in _parse_url
oasis-1   |     raise ValueError("Please specify a container name.")
oasis-1   | ValueError: Please specify a container name.
oasis-1   | 2025-03-11 13:41:59,117 - ERROR - Internal Server Error: /api/oasis/cases/806f90c2-6963-4b9d-b269-32014f1e95d7
oasis-1   | Traceback (most recent call last):
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
oasis-1   |     response = get_response(request)
oasis-1   |                ^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/debug_toolbar/middleware.py", line 97, in __call__
oasis-1   |     rendered = toolbar.render_toolbar()
oasis-1   |                ^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/debug_toolbar/toolbar.py", line 84, in render_toolbar
oasis-1   |     return render_to_string("debug_toolbar/base.html", context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
oasis-1   |     return template.render(context, request)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
oasis-1   |     return self.template.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 171, in render
oasis-1   |     return self._render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
oasis-1   |     return self.nodelist.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
oasis-1   |     return SafeString("".join([node.render_annotated(context) for node in self]))
oasis-1   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
oasis-1   |     return self.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 56, in render
oasis-1   |     result = self.nodelist.render(context)
oasis-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
oasis-1   |     return SafeString("".join([node.render_annotated(context) for node in self]))
oasis-1   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
oasis-1   |     return self.render(context)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/templatetags/static.py", line 116, in render
oasis-1   |     url = self.url(context)
oasis-1   |           ^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/templatetags/static.py", line 113, in url
oasis-1   |     return self.handle_simple(path)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/django/templatetags/static.py", line 129, in handle_simple
oasis-1   |     return staticfiles_storage.url(path)
oasis-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/debug_toolbar/panels/staticfiles.py", line 63, in url
oasis-1   |     return super().url(path)
oasis-1   |            ^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/storages/backends/azure_storage.py", line 320, in url
oasis-1   |     container_blob_url = self.client.get_blob_client(name).url
oasis-1   |                          ^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/storages/backends/azure_storage.py", line 198, in client
oasis-1   |     self._client = self.service_client.get_container_client(
oasis-1   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_blob_service_client.py", line 724, in get_container_client
oasis-1   |     return ContainerClient(
oasis-1   |            ^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_container_client.py", line 142, in __init__
oasis-1   |     parsed_url, sas_token = _parse_url(account_url=account_url, container_name=container_name)
oasis-1   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oasis-1   |   File "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_container_client_helpers.py", line 32, in _parse_url
oasis-1   |     raise ValueError("Please specify a container name.")
oasis-1   | ValueError: Please specify a container name.
```

**Comment by unreal91** [comment]
@jschneier I think the issue is how you reading the container_name, I am not setting AZURE_CONTAINER as part of environment variable, it is in the options for each, as for media and static are different containers.

**Comment by piotrjez** [comment]
The problem is a bug in the `django-debug-toolbar` library, which has been fixed within: https://github.com/django-commons/django-debug-toolbar/pull/2097
Updating `django-debug-toolbar` to the latest version should fix the problem.
