### ISSUE TITLE
Cannot open same S3File instance using different modes

### ISSUE THREAD

**Issue by devmonkey22** [jschneier/django-storages#1474]
I'm using `S3Storage` backend with a Django model with a `FileField` field.  With a model instance with a FileField tied to this storage, I need to be able to open (read) the same file as text and later binary (i.e. to compute hash) from the same model instance.  However,         Django `FileField`s (really `FieldFile`s) keep a reference to the underlying `File` (aka `S3File`) even after closing which makes it require being able to reopen with a different mode.  When closed, the `S3File._file` is cleared out, but `S3File._mode` remains, thus preventing a future open from changing modes before it opens the file again.

Currently I receive the [S3File.open error "Cannot reopen file with a new mode."](https://github.com/jschneier/django-storages/blob/f029e50eeddb0c9b8c1c1ba110a60a92df188c44/storages/backends/s3.py#L152C31-L152C66) which was added in #1321 to fix #1319 and released in version 1.14.2.

Example Code:
```python
data = "abcdefghijklmnopqrstuvwxyz\n"
model = SomeModel.objects.create()
model.file_contents.save("data.txt", ContentFile(data*2))

# Simulate reading binary (to compute SHA256)
sha_hash = hashlib.new('sha256')
with model.file_contents.open('rb') as f:
	for chunk in f.chunks():
		sha_hash.update(chunk)

# This fails with ValueError: Cannot reopen file with a new mode.
with model.file_contents.open('r') as f:
	line_count = 0
	for line in f.readlines():
		self.assertEqual(line, data)
		line_count += 1
	self.assertEqual(line_count, 2)
```

This raises:
```
Traceback (most recent call last):
  File ".../test_models.py", line 233, in test_s3_reopen
    with msg.data.open('r') as f:
  File ".../python3.10/site-packages/django/db/models/fields/files.py", line 81, in open
    self.file.open(mode)
  File ".../python3.10/site-packages/storages/backends/s3.py", line 152, in open
    raise ValueError("Cannot reopen file with a new mode.")
ValueError: Cannot reopen file with a new mode.
```

I'll push a PR shortly that should resolve this.  Let me know if it causes unintended issues allowing `S3File` to be reopened that I didn't notice.

**Comment by janosroden** [comment]
This isn't a fully `django-storage` issue, it's a combination of the behavior of `S3File` and its usage.

If we're talking about `S3File` only, then yes, it would be nice to reopen it with a different mode. However, it gets the access mode in the `__init__()` too and checks if the file can be read (...why?). Not opening a file in `open()` is weird on its own, but I guess the author had his reasons.

On the other hand, django's `FieldFile` keeps the `S3File` instance even after close, which is okay in general, but in this case, the `mode` passed to the constructor, so this approach fails. This is up to the `Storage` though.

Also note that `FieldFile.open()` doesn't return a context manager (returns `self` instead).

All in all, here is how you can reopen an s3 file:

```python
f = model.file_contents.open(...)
try:
    # work
finally:
    f.close()
    del model.file_contents.file
```
