### ISSUE TITLE
import urllib2 ImportError: No module named 'urllib2'

### ISSUE THREAD

**Issue by darkicex3** [jschneier/django-storages#161]
I've this error when I am running python3 manage.py collectstatic :     

Debian 8, Google Compute Engine, Python3.4

```
Traceback (most recent call last):
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/storages/backends/s3boto.py", line 13, in <module>
    from boto import __version__ as boto_version
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "/usr/share/google/boto/boto_plugins/compute_auth.py", line 18, in <module>
    import urllib2
ImportError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    return module.Command()
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 32, in __init__
    self.storage.path('')
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/django/utils/functional.py", line 204, in inner
    self._setup()
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 394, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/django/core/files/storage.py", line 328, in get_storage_class
    return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/var/www/kbsv3/kbsv3_env/lib/python3.4/site-packages/storages/backends/s3boto.py", line 19, in <module>
    raise ImproperlyConfigured("Could not load Boto's S3 bindings.\n"
django.core.exceptions.ImproperlyConfigured: Could not load Boto's S3 bindings.
See https://github.com/boto/boto
```

**Comment by jschneier** [comment]
This seems to be a Python 2/3 issue with Google Cloud. The [tracking bug](https://github.com/GoogleCloudPlatform/compute-image-packages/pull/213) for the issue what you want seems to indicate it is fixed everywhere but Debian and will be fixed there soon. Good luck!
