### ISSUE TITLE
Small PNGs fail to upload to S3

### ISSUE THREAD

**Issue by lmanzurv** [jschneier/django-storages#178]
When trying to upload small PNGs (like those used for Favicons - 32x32), it generates an StringIO instance has no attribute 'size' error.

This is the error trace:

```
ERROR Internal Server Error: /en/admin/filer/clipboard/operations/upload/no_folder/
Traceback (most recent call last):
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/filer/admin/clipboardadmin.py", line 123, in ajax_upload
    file_obj.save()
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/filer/models/imagemodels.py", line 55, in save
    super(Image, self).save(*args, **kwargs)
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/filer/models/abstract.py", line 67, in save
    super(BaseImage, self).save(*args, **kwargs)
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/filer/models/filemodels.py", line 171, in save
    super(File, self).save(*args, **kwargs)
File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/polymorphic/models.py", line 90, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 761, in save_base
    self._save_parents(cls, using, update_fields)
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 786, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db
/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 973, in execute_sql
    for sql, params in self.as_sql():
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 931, in as_sql
    for obj in self.query.objs
  File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 314, in pre_save
    file.save(file.name, file, save=False)
  **File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/filer/fields/multistorage_file.py", line 95, in save
    super(MultiStorageFieldFile, self).save(name, content, save)**
  **File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 670, in save
    super(ThumbnailerFieldFile, self).save(name, content, *args, **kwargs)**
  **File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 106, in save
    self._size = content.size**
File "/home/ec2-user/envs/soft-env/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 75, in _get_size
    return self.file.size
**AttributeError: StringIO instance has no attribute 'size'**
```

This happens when using Django==1.8.9, django-storages==1.4.1 and boto==2.41.0.

**Comment by jschneier** [comment]
Hi and thanks for the report. A [PR](https://github.com/jschneier/django-storages/pull/74) was submitted for what I think is the same issue (although I don't completely understand it yet). Mind trying that out and seeing if that fixes your issue?
