### ISSUE TITLE
collectstatic fails with S3Boto3Storage due to timezone

### ISSUE THREAD

**Issue by m4ra** [jschneier/django-storages#191]
With django 1.10, python 3.5, postgresql 9.5 and USE_TZ = True, collectfiles fails with
`make_aware expects a naive datetime, got %s" % value)
ValueError: make_aware expects a naive datetime, got 2016-08-19 13:28:40+00:00`

If USE_TZ = False, collectstatic fails with   
`File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 276, in delete_file
    if (target_last_modified.replace(microsecond=0) >= source_last_modified.replace(microsecond=0) and TypeError: can't compare offset-naive and offset-aware datetimes`

My settings
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

This doesn't happen when I use boto and s3boto.S3BotoStorage.
Any ideas?
Thanx

Traceback (USE_TZ = True):
```
(genv) luna% python manage.py collectstatic --noinput
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 193, in handle
    collected = self.collect()
  File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 337, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 258, in delete_file
    target_last_modified = self.storage.get_modified_time(prefixed_path)
  File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/core/files/storage.py", line 231, in get_modified_time
    return _possibly_make_aware(dt)
  File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/core/files/storage.py", line 243, in _possibly_make_aware
    return timezone.make_aware(dt, tz).astimezone(timezone.utc)
  File "/home/mara/webdev/genv/lib/python3.5/site-packages/django/utils/timezone.py", line 373, in make_aware
    "make_aware expects a naive datetime, got %s" % value)
ValueError: make_aware expects a naive datetime, got 2016-08-19 `13:28:40+00:00
```

**Comment by jschneier** [comment]
Hi and thanks for the report. A contributor added support for `get_modified_time` about a week ago. Can you test against current master and see if that fixes your issue?

**Comment by m4ra** [comment]
Yes, that works! Thank you.

**Comment by jschneier** [comment]
Glad to hear, I'll release a 1.5.1 sometime this week.
