### ISSUE TITLE
SFTP problem

### ISSUE THREAD

**Issue by adi-** [jschneier/django-storages#199]
I get this error:
```
File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/paramiko/client.py", line 70, in __init__
    self._system_host_keys = HostKeys()
RecursionError: maximum recursion depth exceeded
```

which really doesn't say much about the real problem. I know that there is a mkdir loop, but what causes it?

**Comment by ZuluPro** [comment]
@adi- Thank for reporting this error, I'll look at it deeper this evening.
Can you give us more about how you configure it ?

**Comment by adi-** [comment]
The basic I have started with was:

```python
DBBACKUP_STORAGE = 'storages.backends.sftpstorage.SFTPStorage'
DBBACKUP_STORAGE_OPTIONS = {
  'host': '__server_address__',
  'params': {
    'username': '__username__',
    'password': '__password__',
  }
}
```

I have also tried setting custom `root_path`, `file_mode`, 'dir_mode` but without any luck.

**Comment by ZuluPro** [comment]
Could we also have the full traceback ?

**Comment by adi-** [comment]
```
$ ./manage.py dbbackup

Backing Up Database: ***
Backup size: 1.1 KiB
Writing file to ***-2016-09-08-121004.psql
Writing file ***-2016-09-08-121004.psql
Writing file ***-2016-09-08-121004.psql
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)   
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/dbbackup/utils.py", line 99, in wrapper
    func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/dbbackup/management/commands/dbbackup.py", line 55, in handle
    self._save_new_backup(database)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/dbbackup/management/commands/dbbackup.py", line 81, in _save_new_backup
    self.write_to_storage(outputfile, filename)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/dbbackup/management/commands/_base.py", line 83, in write_to_storage
   self.storage.write_file(file, path)   
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/dbbackup/storage.py", line 82, in write_file
    self.storage.save(name=filename, content=filehandle)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 132, in _save
    self._mkdir(dirname)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 117, in _mkdir
    self._mkdir(parent)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 117, in _mkdir
    self._mkdir(parent)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 117, in _mkdir
    self._mkdir(parent)

[...]

  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 117, in _mkdir
    self._mkdir(parent)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 117, in _mkdir
    self._mkdir(parent)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 117, in _mkdir
    self._mkdir(parent)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 117, in _mkdir
    self._mkdir(parent)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 117, in _mkdir
    self._mkdir(parent)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 116, in _mkdir
    if not self.exists(parent):
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 153, in exists
    self.sftp.stat(remote_path)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 85, in sftp
    self._connect()
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 51, in _connect
    self._ssh = paramiko.SSHClient()
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/paramiko/client.py", line 70, in __init__
    self._system_host_keys = HostKeys()   
RecursionError: maximum recursion depth exceeded
```

**Comment by jbittel** [comment]
I've not discovered the exact cause, but I was able to resolve this problem by setting SFTP_KNOWN_HOST_FILE with a path to a file containing the host keys for the target server. If there's a better or simpler way to resolve this, I'd be interested.

Thanks!

**Comment by adi-** [comment]
Still doesn't work. Could you paste your settings here?

**Comment by aheld** [comment]
Using a a windows path I can replicate this defect.  the code checks if the parent exists, and if not then it tries to create it.

Using a windows path the 'dirname' becomes and empty string, and then calling "exists" on an empty string says that it does not exist and tries to create it.  --  infinite loop. 

```
>>> posixpath.dirname('/home/user')
'/home'
>>> posixpath.dirname('home\user')
''
>>> sfpBackend.exists('')
False
>>> sf._mkdir('\home\aheld\test')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/aheld/.virtualenvs/low_income/src/django-storages/storages/backends/sftpstorage.py", line 117, in _mkdir
    self._mkdir(parent)
  File "/Users/aheld/.virtualenvs/low_income/src/django-storages/storages/backends/sftpstorage.py", line 117, in _mkdir
    self._mkdir(parent)
  File "/Users/aheld/.virtualenvs/low_income/src/django-storages/storages/backends/sftpstorage.py", line 117, in _mkdir

...

RuntimeError: maximum recursion depth exceeded in __instancecheck__
```

**Comment by jschneier** [comment]
@aheld interesting. @adi- can you confirm that the target system is a Windows box?

I noticed that we explicitly don't support it in the codebase but we could pretty easily add an optional dependency (for SFTP only) on `backports.pathlib` for the pre-3.4 versions.

**Comment by adi-** [comment]
Ubuntu 16.04 ;)

**Comment by aheld** [comment]
what is the path?anything IOError will also put this into an infinite loop

**Comment by jbittel** [comment]
Here's the settings I'm using, and both the source and target servers are Ubuntu:

```
SFTP_STORAGE_HOST = '<hostname>'
SFTP_STORAGE_ROOT = '/var/www/media/'
SFTP_STORAGE_PARAMS = {
    'username': '<username>',
    'password': '<password>',
    'allow_agent': False,
    'look_for_keys': False,
}
SFTP_KNOWN_HOST_FILE = '/var/www/data/known_hosts'
SFTP_STORAGE_INTERACTIVE = False
```

As I said above, if I remove the `SFTP_KNOWN_HOST_FILE` setting, or remove the file it points to, then I get the same infinite loop. Also note that the `known_hosts` file must have the correct restrictive permissions or it will not be used. I've verified that the path is correct and if you look at the full traceback you can see the recursion walking up the path one directory at a time until it reaches `/`.

**Comment by ZuluPro** [comment]
I think the real trouble is here: https://github.com/jschneier/django-storages/blob/master/storages/backends/sftpstorage.py#L78

We catch all exception without raise critical errors. Let me sometime to make a better try/except block

**Comment by adi-** [comment]
@jbittel How come you are using `SFTP_` settings. Django-storages doesn't use those settings nor paramiko.

**Comment by adi-** [comment]
@jbittel ahhh, my bad. There is such an option. However, with your settings I cannot make it work either :(

**Comment by adi-** [comment]
Ok, make it work finally!

It will be good to mention about `known_host_file` in docs as in https://github.com/django-dbbackup/django-dbbackup/issues/220

**Comment by adi-** [comment]
So, this seems to be a duplicate of: https://github.com/jschneier/django-storages/issues/118

**Comment by adi-** [comment]
Closing...
