### ISSUE TITLE
MemoryError on large (400MB+) files

### ISSUE THREAD

**Issue by adi-** [jschneier/django-storages#213]
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)   
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_com
mand_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/srv/gazex/gazex/core/management/commands/backup_stg.py", line 13, in handle
    call_command("mediabackup", compress=True, clean=True, servername="gazex-www-stg")
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/dbbackup/utils.py", line 99, in wrapper
    func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/dbbackup/management/commands/mediabackup.py", line 46, in handle
    self.backup_mediafiles()
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/dbbackup/management/commands/mediabackup.py", line 96, in backup_mediafiles
    self.write_to_storage(tarball, filename)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/dbbackup/management/commands/_base.py", line 82, in write_to_storage  
    self.storage.write_file(file, path)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/dbbackup/storage.py", line 82, in write_file
    self.storage.save(name=filename, content=filehandle)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/storages/backends/sftpstorage.py", line 139, in _save
    f.write(content.file.read())
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/paramiko/file.py", line 381, in write
    self._write_all(data)
  File "/home/vagrant/.virtualenvs/gazex/lib/python3.5/site-packages/paramiko/file.py", line 499, in _write_all
    data = data[count:]
MemoryError
```

**Comment by ZuluPro** [comment]
@adi- 
Thank for reporting this issue, I'll look deeper soon.

**Comment by adi-** [comment]
So, I have looked into this, but there is some more logic I don't understand for now. I am afraid I can't make it work in a good way.  However, the `self.sftp.putfo(content, path)` should be used there, so maybe someone could fix it the right way.

**Comment by jschneier** [comment]
Closed by a26eeadbcbc0a9a22d12a2da99484d4531741ac5.

**Comment by Natureshadow** [comment]
This issue still persists; the commit linked in the comment above is not in any branch of the repository and not in any release.

@jschneier can you please reopen the bug, and, if possible reinvestigate? This breakes backups in django-dbbackup in our AlekSIS project.

**Comment by debdolph** [comment]
Any progress/

**Comment by jschneier** [comment]
Resolved long ago by using `putfo`.
