### ISSUE TITLE
Error when using boto 2.46.0

### ISSUE THREAD

**Issue by cnk** [jschneier/django-storages#270]
I recently deleted and rebuilt my VM (Ubuntu 16.04 LTS) and pip installed boto 2.46.0 rather than 2.45.0 that I had had previously. One of the changes in that version is adding boto.vendored.regions to boto's setup.py https://github.com/boto/boto/pull/3682/files That triggers the following error. I am filing the issue here because I am assuming there is something odd with the way boto-storages is importing rather than there being a more general error that boto 2.46.0 is unusable. What do you think? Please close this if you disagree and think storages should work with the new boto

```
[10.1.99.100] out: Preparing Django
[10.1.99.100] out: Traceback (most recent call last):
[10.1.99.100] out:   File "/srv/mereokratos/mk_web_core/ve/lib/python3.5/site-packages/storages/backends/s3boto.py", line 13, in <module>
[10.1.99.100] out:     from boto import __version__ as boto_version
[10.1.99.100] out:   File "/srv/mereokratos/mk_web_core/ve/lib/python3.5/site-packages/boto/__init__.py", line 28, in <module>
[10.1.99.100] out:     from boto.storage_uri import BucketStorageUri, FileStorageUri
[10.1.99.100] out:   File "/srv/mereokratos/mk_web_core/ve/lib/python3.5/site-packages/boto/storage_uri.py", line 27, in <module>
[10.1.99.100] out:     from boto.s3.deletemarker import DeleteMarker
[10.1.99.100] out:   File "/srv/mereokratos/mk_web_core/ve/lib/python3.5/site-packages/boto/s3/__init__.py", line 26, in <module>
[10.1.99.100] out:     from boto.regioninfo import RegionInfo, get_regions
[10.1.99.100] out:   File "/srv/mereokratos/mk_web_core/ve/lib/python3.5/site-packages/boto/regioninfo.py", line 28, in <module>
[10.1.99.100] out:     from boto.endpoints import BotoEndpointResolver
[10.1.99.100] out:   File "/srv/mereokratos/mk_web_core/ve/lib/python3.5/site-packages/boto/endpoints.py", line 13, in <module>
[10.1.99.100] out:     import boto.vendored.regions.regions as _regions
[10.1.99.100] out: ImportError: No module named 'boto.vendored.regions'
```

**Comment by Alex3917** [comment]
I'm not getting any errors with 2.46.1, although we might not be using it the same way.

**Comment by jschneier** [comment]
Hi and thanks for the report. I think that boto 2.46 was simply a badly release that has been basically pulled. If you look at [the release notes of boto](http://docs.pythonboto.org/en/latest/#release-notes) you can see that 2.46 isn't even listed, the versions go straight from 2.45 to 2.46.1.
