### ISSUE TITLE
Method isdir is not implemented.

### ISSUE THREAD

**Issue by eltonplima** [jschneier/django-storages#286]
- django: 1.10.6
- django-storages: 1.5.2
- django-filebrowser-no-grappelli: 1.5.2

When I use [django-filebrowser](https://github.com/smacker/django-filebrowser-no-grappelli) the exception AttributeError(**has no attribute 'isdir'**) is raised.

This is the traceback:

`
Internal Server Error: /admin/filebrowser/browse/
Traceback (most recent call last):
  File "/home/eltonplima/MEGA/itcglobal/planejeme/.venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/eltonplima/MEGA/itcglobal/planejeme/.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/eltonplima/MEGA/itcglobal/planejeme/.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eltonplima/MEGA/itcglobal/planejeme/.venv/lib/python3.6/site-packages/filebrowser/decorators.py", line 35, in decorator
    if get_path('', site=site) is None:
  File "/home/eltonplima/MEGA/itcglobal/planejeme/.venv/lib/python3.6/site-packages/filebrowser/decorators.py", line 18, in get_path
    if site.storage.isdir(converted_path):
  File "/home/eltonplima/MEGA/itcglobal/planejeme/.venv/lib/python3.6/site-packages/django/utils/functional.py", line 235, in inner
    return func(self._wrapped, *args)
AttributeError: 'DropBoxStorage' object has no attribute 'isdir'
`

**Is this a bug in django-storages or should this method not exist anyway?**

**Comment by jschneier** [comment]
Hi. If you read the [filebrowser docs for storage](https://django-filebrowser.readthedocs.io/en/latest/admin.html) you'll see that filebrowser provides a mixin that you need to add to whatever storage backend you'd like to use. So making your setting point to something like:
```python
class MyStorage(filebrowser.storage.StorageMixin, DropBoxStorage):
    pass
```
should do it.
