### ISSUE TITLE
Unable to set/use GS_CREDENTIALS for connection to Google Cloud Storage

### ISSUE THREAD

**Issue by prdonahue** [jschneier/django-storages#353]
Unclear based on the docs what GS_CREDENTIALS is supposed to be set to? 

The [docs](http://django-storages.readthedocs.io/en/latest/backends/gcloud.html) simply say:

> GS_CREDENTIALS (optional)
> 
> The OAuth 2 credentials to use for the connection. If unset, falls back to the default inferred from the environment.
> 

After creating a service key with the appropriate permissions and downloading as a JSON file I've tried:

* base64 encoding the contents and setting that as GS_CREDENTIALS
* setting GS_CREDENTIALS to the path to that JSON file
* setting the GOOGLE_APPLICATION_CREDENTIALS environment variable to same path

The last attempt (GOOGLE_APPLICATION_CREDENTIALS) indicates:
```
ValueError: This library only supports credentials from google-auth-library-python. See https://google-cloud-python.readthedocs.io/en/latest/core/auth.html for help on authentication with this library.
```

Those instructions ultimately link here: https://cloud.google.com/storage/docs/authentication#generating-a-private-key.

Other attempts give me:

```
# python manage.py collectstatic --noinput
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/env/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/env/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/env/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/env/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/env/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 260, in delete_file
    if self.storage.exists(prefixed_path):
  File "/env/src/django-storages/storages/backends/gcloud.py", line 173, in exists
    return bool(self.bucket.get_blob(self._encode_name(name)))
  File "/env/src/django-storages/storages/backends/gcloud.py", line 113, in bucket
    self._bucket = self._get_or_create_bucket(self.bucket_name)
  File "/env/src/django-storages/storages/backends/gcloud.py", line 121, in _get_or_create_bucket
    return self.client.get_bucket(name)
  File "/env/src/django-storages/storages/backends/gcloud.py", line 106, in client
    credentials=self.credentials
  File "/env/lib/python3.6/site-packages/google/cloud/storage/client.py", line 59, in __init__
    _http=_http)
  File "/env/lib/python3.6/site-packages/google/cloud/client.py", line 223, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/env/lib/python3.6/site-packages/google/cloud/client.py", line 177, in __init__
    project = self._determine_default(project)
  File "/env/lib/python3.6/site-packages/google/cloud/client.py", line 190, in _determine_default
    return _determine_default_project(project)
  File "/env/lib/python3.6/site-packages/google/cloud/_helpers.py", line 181, in _determine_default_project
    _, project = google.auth.default()
  File "/env/lib/python3.6/site-packages/google/auth/_default.py", line 282, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or
explicitly create credential and re-run the application. For more
information, please see
https://developers.google.com/accounts/docs/application-default-credentials.
```

**Comment by prdonahue** [comment]
User error—please close.

**Comment by camflan** [comment]
@prdonahue how did you resolve this? I did all of those same things as well, which lead me here. The documentation is not clear to me
