### ISSUE TITLE
SFTPStorage doesn't reconnect after ssh connection is closed

### ISSUE THREAD

**Issue by mnach** [jschneier/django-storages#563]
We faced with this issue in one of our projects. 
After storage server reboots celery workers tries to save files using socket to ssh-connection which have been closed.
I want to add reconnect logic in this class (I will send a PR)

```
Traceback (most recent call last):
  File "/app/python/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/python/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/project/demo_app/tasks.py", line 20, in check_storage_task
    text = obj.data.read().decode()
  File "/app/python/lib/python3.6/site-packages/storages/backends/sftpstorage.py", line 217, in read
    self.file = self._storage._read(self._name)
  File "/app/python/lib/python3.6/site-packages/storages/backends/sftpstorage.py", line 104, in _read
    return self.sftp.open(remote_path, 'rb')
  File "/app/python/lib/python3.6/site-packages/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/app/python/lib/python3.6/site-packages/paramiko/sftp_client.py", line 729, in _request
    num = self._async_request(type(None), t, *arg)
  File "/app/python/lib/python3.6/site-packages/paramiko/sftp_client.py", line 754, in _async_request
    self._send_packet(t, msg)
  File "/app/python/lib/python3.6/site-packages/paramiko/sftp.py", line 170, in _send_packet
    self._write_all(out)
  File "/app/python/lib/python3.6/site-packages/paramiko/sftp.py", line 133, in _write_all
    n = self.sock.send(out)
  File "/app/python/lib/python3.6/site-packages/paramiko/channel.py", line 767, in send
    return self._send(s, m)
  File "/app/python/lib/python3.6/site-packages/paramiko/channel.py", line 1133, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed
```

**Comment by mnach** [comment]
@jschneier 
Hi!
Is there some plans for releasing this bugfix in next minor version 1.7.2 ? 
it's not so pretty to have a link to github in our requirements  file

**Comment by jschneier** [comment]
I believe this made it into 1.7.1?

**Comment by mnach** [comment]
Yep! Sorry, my bad..
