### ISSUE TITLE
"Server failed to authenticate the request" Azure backend

### ISSUE THREAD

**Issue by richardARPANET** [jschneier/django-storages#808]
Python 3.7.4

```
django-storages==1.8  # i also tried master on github 
azure-storage-blob==2.1.0
```

```
2019-12-31 12:31:06,977 - health-check - ERROR - unavailable: Unknown exception
Traceback (most recent call last):
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/lib/python3.7/site-packages/health_check/storage/backends.py", line 65, in check_status
    file_name = self.check_save(file_name, file_content)
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/lib/python3.7/site-packages/health_check/storage/backends.py", line 43, in check_save
    file_name, ContentFile(content=file_content)
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/lib/python3.7/site-packages/django/core/files/storage.py", line 51, in save
    name = self.get_available_name(name, max_length=max_length)
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/src/django-storages/storages/backends/azure_storage.py", line 215, in get_available_name
    return super(AzureStorage, self).get_available_name(name, max_length)
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/lib/python3.7/site-packages/django/core/files/storage.py", line 82, in get_available_name
    while self.exists(name) or (max_length and len(name) > max_length):
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/src/django-storages/storages/backends/azure_storage.py", line 221, in exists
    timeout=self.timeout)
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 1763, in exists
    _dont_fail_not_exist(ex)
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/lib/python3.7/site-packages/azure/storage/common/_error.py", line 97, in _dont_fail_not_exist
    raise error
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 1759, in exists
    self._perform_request(request, expected_errors=expected_errors)
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request
    raise ex
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request
    raise ex
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 360, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/home/work/.pyenv/versions/3.7.4/envs/data-samples-service/lib/python3.7/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: AuthenticationFailed
```

I'm using https://github.com/KristianOellegaard/django-health-check

Which uses django-storages. When using a valid tested account key and the following django settings. Note that I have tried using the `az` cli tool with these params and it works fine, so the issue is the Python code.

The below key is mine with alphanumeric chars replaced with x

```
AZURE_ACCOUNT_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx+xxxxxxx/xxx+x==
AZURE_ACCOUNT_NAME=exampleaccount
AZURE_CONTAINER=example
AZURE_CUSTOM_DOMAIN=example.blob.core.windows.net
```

Am i doing something wrong/any ideas?

**Comment by richardARPANET** [comment]
This was my fault actually. I had `AZURE_EMULATED_MODE` set to `True` in my Django settings :)
