### ISSUE TITLE
ManifestFilesMixin

### ISSUE THREAD

**Issue by thisboyiscrazy** [jschneier/django-storages#841]
I am not sure if this is an issue with S3Boto3Storage or ManifestFilesMixin

I am using:
```
Django==3.0
django_storages==1.9.1
```

But if I try:
```
from django.conf import settings

from django.contrib.staticfiles.storage import ManifestFilesMixin
from storages.backends.s3boto3 import S3Boto3Storage

class StaticStorage(ManifestFilesMixin,S3Boto3Storage):
    pass
```

I get:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 161, in handle
    if self.is_local_storage() and self.storage.location:
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 215, in is_local_storage
    return isinstance(self.storage, FileSystemStorage)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 501, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 379, in __init__
    self.hashed_files = self.load_manifest()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 389, in load_manifest
    content = self.read_manifest()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 383, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/usr/local/lib/python3.7/site-packages/django/core/files/storage.py", line 36, in open
    return self._open(name, mode)
  File "/usr/local/lib/python3.7/site-packages/storages/backends/s3boto3.py", line 526, in _open
    raise IOError('File does not exist: %s' % name)
OSError: File does not exist: static/staticfiles.json
```

It seems S3Boto3Storage is throwing `IOError` but ManifestFilesMixin is expecting `FileNotFound`

This seems to fix it:

```
class StaticStorage(ManifestFilesMixin,S3Boto3Storage):
    
    # FIXME this seems to be a bug in ManifestFilesMixin with S3Boto3Storages
    # ManifestFilesMixin is expecting a FileNotFound error but
    # S3Boto3Storages is throwing an IOError
    def read_manifest(self):
        try:
            return super(StaticStorage,self).read_manifest()
        except IOError:
            return None
```

**Comment by jschneier** [comment]
FileNotFoundError is a subclass of OSError and is in Python 3.3+ which is when IOError was folded into OSError.

**Comment by thisboyiscrazy** [comment]
For reference i am using python 3.7

**Comment by sid22** [comment]
Bump for this issue.
When I run 
`python manage.py collectstatic`

With this for uploading to S3, I get exact same error.

> Traceback (most recent call last):
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/storages/backends/s3boto3.py", line 523, in _open
    f = S3Boto3StorageFile(name, mode, self)
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/storages/backends/s3boto3.py", line 74, in __init__
    self.obj.load()
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 161, in handle
    if self.is_local_storage() and self.storage.location:
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 215, in is_local_storage
    return isinstance(self.storage, FileSystemStorage)
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 501, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 379, in __init__
    self.hashed_files = self.load_manifest()
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 389, in load_manifest
    content = self.read_manifest()
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 383, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/django/core/files/storage.py", line 36, in open
    return self._open(name, mode)
  File "/Users/i0714/Desktop/dev-portal/venv/lib/python3.6/site-packages/storages/backends/s3boto3.py", line 526, in _open
    raise IOError('File does not exist: %s' % name)
OSError: File does not exist: static/staticfiles.json

**Comment by amrael** [comment]
I ran into this issue and fixed it like this,

```
class ManifestS3Boto3Storage(ManifestFilesMixin, S3Boto3Storage):
    def _open(self, name, mode='rb'):
        name = self._normalize_name(self._clean_name(name))
        try:
            f = S3Boto3StorageFile(name, mode, self)
        except ClientError as err:
            if err.response['ResponseMetadata']['HTTPStatusCode'] == 404:
                raise FileNotFoundError('File does not exist: %s' % name)
            raise  # Let it bubble up if it was some other error
        return f

```
The class merely overrides `_open` function to raise FileNotFoundError instead of IOError which causes the first `collectstatic` command to fail.

I'm using Python 3.8.2 and Django 3.0.5

**Comment by kimbuckley** [comment]
I also ran into this exact same issue and the following fixed it for me as well.
`
class ManifestStaticFilesStorage(ManifestFilesMixin, S3Boto3Storage):
    bucket_name = settings.STATIC_FILES_BUCKET
    location = settings.STATIC_FILES_LOCATION

    def read_manifest(self):
        try:
            return super(ManifestStaticFilesStorage,self).read_manifest()
        except IOError:
            return None
`

**Comment by vchrisb** [comment]
the mentioned fix also worked with `GoogleCloudStorage`
```
    def read_manifest(self):
        try:
            return super(StaticStorage,self).read_manifest()
        except IOError:
            return None
```

**Comment by jschneier** [comment]
This has been fixed in the latest releases.
