### ISSUE TITLE
""Unicode-objects must be encoded before hashing" when i try upload a .m3u8 file using storages|s3 instead local storage. 

### ISSUE THREAD

**Issue by flakesrc** [jschneier/django-storages#869]
**Describe the bug**

**COMPLETE CODE AND SETTINGS IN THE END OF THE FILE**
**the upload works when i add the .m3u8 file directly in the aws s3 site**

I was able to send the video normally to my local machine, but when I changed the storage settings, I just started getting this error.

The error points to the line where the code is
```
instance.file.save(file_name_m3u8, file_m3u8)
```

And then immediately points to

```
     .../python3.8/site-packages/storages/backends/s3boto3.py
    ...
    obj.upload_fileobj(content, ExtraArgs=params) 
    ...
```

My file object `file_m3u8` is:

```
    file_object  
    <_io.TextIOWrapper name='/tmp/media/lectures/first_video_2/2020-04-04_16-11-20.m3u8' mode='r' encoding='UTF-8'>
```
Example:
```
    from django.db.models.signals import post_save
    from django.dispatch import receiver
    from django.core.files import File
    from .models import Lecture
  
    
    @receiver(post_save, sender=Lecture) 
    def handle_video_upload (sender, instance, created, ** kwargs):
             with open (  
    "/tmp/media/lectures/first_video_2/2020-04-04_16-11-20.m3u8", "r") as file_object:
                 file_m3u8 = File (
                     name = "media/lectures/first_video_2/2020-04-04_16-11-20.m3u8",
                     file = file_object)
                 instance.file.save ("2020-04-04_16-11-20.m3u8", file_m3u8)
```

I'm using django-storages and settings this in my settings.py file:

```
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")

CLOUDFRONT_ID = config("CLOUDFRONT_ID")
CLOUDFRONT_DOMAIN = f"{CLOUDFRONT_ID}.cloudfront.net"
AWS_S3_CUSTOM_DOMAIN = f"{CLOUDFRONT_ID}.cloudfront.net"
```

**Expected behavior**
i expect that the file will be uploaded normally

**Debug logs**
terminal output:

```
[05/Apr/2020 17:42:30] "GET /admin/jsi18n/ HTTP/1.1" 200 7275
/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/storages/backends/s3boto3.py:340: UserWarning: The default behavior of S3Boto3Storage is insecure and will change in django-storages 1.10. By default files and new buckets are saved with an ACL of 'public-read' (globally publicly readable). Version 1.10 will default to using the bucket's ACL. To opt into the new behavior set AWS_DEFAULT_ACL = None, otherwise to silence this warning explicitly set AWS_DEFAULT_ACL.
  warnings.warn(
[05/Apr/2020 17:42:32] "GET /admin/lectures/lecture/5/change/ HTTP/1.1" 200 6712
[05/Apr/2020 17:42:32] "GET /admin/jsi18n/ HTTP/1.1" 200 7275
/tmp/media/lectures/first_video_2/2020-04-04_16-11-20.m3u8
2020-04-04_16-11-20.m3u8
Internal Server Error: /admin/lectures/lecture/5/change/
Traceback (most recent call last):
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1641, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1081, in save_model
    obj.save()
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/db/models/base.py", line 793, in save_base
    post_save.send(
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/marcos/geeknoon/geeknoon_server/lectures/signals.py", line 90, in handle_video_upload
    instance.file.save(file_name_m3u8, file_m3u8)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/db/models/fields/files.py", line 87, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/django/core/files/storage.py", line 52, in save
    return self._save(name, content)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 547, in _save
    obj.upload_fileobj(content, ExtraArgs=params)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/boto3/s3/inject.py", line 619, in object_upload_fileobj
    return self.meta.client.upload_fileobj(
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/botocore/client.py", line 602, in _make_api_call
    handler, event_response = self.meta.events.emit_until_response(
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/botocore/hooks.py", line 360, in emit_until_response
    return self._emitter.emit_until_response(aliased_event_name, **kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/botocore/hooks.py", line 243, in emit_until_response
    responses = self._emit(event_name, kwargs, stop_on_response=True)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/botocore/handlers.py", line 216, in conditionally_calculate_md5
    calculate_md5(params, **kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/botocore/handlers.py", line 194, in calculate_md5
    binary_md5 = _calculate_md5_from_file(body)
  File "/home/marcos/.local/share/virtualenvs/geeknoon_server-HmoJlbqP/lib/python3.8/site-packages/botocore/handlers.py", line 208, in _calculate_md5_from_file
    md5.update(chunk)
TypeError: Unicode-objects must be encoded before hashing
[05/Apr/2020 17:42:39] "POST /admin/lectures/lecture/5/change/ HTTP/1.1" 500 249595
```

## Complete code in signals.py:

```
import subprocess
import os
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.files import File
from pathlib import Path
from .models import Lecture

@receiver(post_save, sender=Lecture)
def handle_video_upload(sender, instance, created, **kwargs):

    file_relative_path = Path(instance.file.name)
    file_suffix = file_relative_path.suffix

    if not file_suffix == '.m3u8' and instance.file_type == "V":
        file_relative_dir = os.path.dirname(instance.file.name)

        file_relative_path_m3u8 = file_relative_path.with_suffix(".m3u8")
        file_name_m3u8 = file_relative_path_m3u8.name

        file_tmp_local_dir = f"/tmp/{file_relative_dir}"
        file_tmp_local_output = f"{file_tmp_local_dir}/{file_name_m3u8}"
        file_cloudfront_url = instance.file.url

        subprocess.run(['mkdir', '-p', file_tmp_local_dir])

        subprocess.run([
            "ffmpeg",
            "-i",
            file_cloudfront_url,
            "-f",
            "hls",
            file_tmp_local_output,
            '-loglevel',
            'quiet'
        ])

        <comment: update the file with the new .m3u8 file>
        with open(file_tmp_local_output, "r") as file_object:
            print(file_tmp_local_output)
            print(file_name_m3u8)
            file_m3u8 = File(name=file_relative_path_m3u8, file=file_object)
            instance.file.save(file_name_m3u8, file_m3u8)
            subprocess.run(["rm", "-r", file_tmp_local_dir])

        boto3.set_stream_logger('')
```

All relevant settings.py vars:

```
INSTALLED_APPS = [
    "storages",
]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
STATIC_ROOT = BASE_DIR.joinpath("local", "static")
MEDIA_ROOT = BASE_DIR.joinpath("local", "media")

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
CLOUDFRONT_ID = config("CLOUDFRONT_ID")
CLOUDFRONT_DOMAIN = f"{CLOUDFRONT_ID}.cloudfront.net"
AWS_S3_CUSTOM_DOMAIN = f"{CLOUDFRONT_ID}.cloudfront.net"
```

What i trying? 
Convert .mkv|.mp4 videos etc after upload, and set the new .m3u8 file in the file field in my model.

I check if this process is needed by checking the file_type and checking if the file was converted by checking if the suffix is the .m3u8.

My model relevant code:

```
from django.db import models
from base_models import CommomInfo # with updated, created and uuid fields

def lecture_file_path(instance, filename):
    return f"media/lectures/{instance.slug}/{filename}"


class Lecture(CommomInfo):
    FILE_TYPE_CHOICES = (("V", "Video"), ("P", "PDF"))
    file = models.FileField(upload_to=lecture_file_path)
    file_type = models.CharField(
        max_length=1,
        choices=FILE_TYPE_CHOICES,
        default="V")
```

**Comment by jschneier** [comment]
Hi. By default `open` will open a text file I believe. Can change the following and tell me what happens:

```python
with open(file_tmp_local_output, "r") as file_object:
```

to

```python
with open(file_tmp_local_output, "rb") as file_object:
```

**Comment by flakesrc** [comment]
> Hi. By default `open` will open a text file I believe. Can you change the following and tell me what happens:
> 
> ```python
> with open(file_tmp_local_output, "r") as file_object:

@jschneier 
> ```
> 
> to
> 
> ```python
> with open(file_tmp_local_output, "rb") as file_object:
> ```

works ,_,
why works when add this? i think that this is needed only in windows

**Comment by jschneier** [comment]
Look at the [docs for open](https://docs.python.org/3.8/library/functions.html?highlight=open#open). With just `r` it assumes text mode and attempts to decode. For storing in the cloud it's just bytes so you need binary mode.
