### ISSUE TITLE
Minnio s3boto3.py: io.UnsupportedOperation: seek

### ISSUE THREAD

**Issue by verschmelzen** [jschneier/django-storages#918]
I am using this library with minio in development and I am getting the following error

```
Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_
     R = retval = fun(*args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __prot
     return self.run(*args, **kwargs)
   File "/app/storage_aggregator/tasks.py", line 141, in fetch_all_images
     fetch_image(prediction)
   File "/app/storage_aggregator/tasks.py", line 125, in fetch_image
     prediction.image.save('new_image.jpeg', response.raw)
   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/files.py", line 8
     self.name = self.storage.save(name, content, max_length=self.field.max_length)
   File "/usr/local/lib/python3.7/site-packages/django/core/files/storage.py", line 52, i
     return self._save(name, content)
   File "/usr/local/lib/python3.7/site-packages/storages/backends/s3boto3.py", line 546,
     content.seek(0, os.SEEK_SET)
 io.UnsupportedOperation: seek
```

I can verify that connection is fine because bucket auto creation works. My settings:
```
AWS_ACCESS_KEY_ID = miniominio
AWS_AUTO_CREATE_BUCKET = True
AWS_DEFAULT_ACL = None
AWS_S3_ENDPOINT_URL = http://minio:9000
AWS_SECRET_ACCESS_KEY = miniominio
AWS_STORAGE_BUCKET_NAME = newbucket
```
Versions:
```
boto3               1.14.47
botocore            1.17.47
Django              3.0.9
django-storages     1.9.1
```

**Comment by verschmelzen** [comment]
The issue was that I was passing non `File` object as content for `FileField.save()`
