### ISSUE TITLE
content.seek(0, os.SEEK_SET) ValueError: I/O operation on closed file.

### ISSUE THREAD

**Issue by Javedgouri** [jschneier/django-storages#945]
Traceback (most recent call last):
  File "/opt/projects/gvs18-beatroute-api/beatroute/common/tests/test_attachmnets.py", line 9, in setUp
    self.attachments = AttachmentFactory.create_batch(5)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/factory/base.py", line 539, in create_batch
    return [cls.create(**kwargs) for _ in range(size)]
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/factory/base.py", line 539, in <listcomp>
    return [cls.create(**kwargs) for _ in range(size)]
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/factory/base.py", line 527, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/factory/django.py", line 117, in _generate
    return super()._generate(strategy, params)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/factory/base.py", line 464, in _generate
    return step.build()
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/factory/builder.py", line 280, in build
    instance = self.factory_meta.instantiate(
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/factory/base.py", line 316, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/factory/django.py", line 166, in _create
    return manager.create(*args, **kwargs)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    for sql, params in self.as_sql():
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1339, in as_sql
    value_rows = [
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1340, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1340, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1291, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/fields/files.py", line 307, in pre_save
    file.save(file.name, file.file, save=False)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/db/models/fields/files.py", line 87, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/django/core/files/storage.py", line 52, in save
    return self._save(name, content)
  File "/opt/projects/gvs18-beatroute-api/venv/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 450, in _save
    content.seek(0, os.SEEK_SET)
ValueError: I/O operation on closed file.

**Comment by jschneier** [comment]
This should be fixed on master.
