### ISSUE TITLE
'NoneType' object has no attribute 'startswith' with SFTP

### ISSUE THREAD

**Issue by rennanflima** [jschneier/django-storages#989]
I have upgraded to 1.11 from 1.9.1. I use the `django-storages[sftp]` and  when I ran the `collectstatic` gave the following error:

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    handler(path, prefixed_path, storage)
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 342, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 249, in delete_file
    if self.storage.exists(prefixed_path):
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/storages/backends/sftpstorage.py", line 151, in exists
    self.sftp.stat(self._remote_path(name))
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/storages/backends/sftpstorage.py", line 87, in sftp
    self._connect()
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/storages/backends/sftpstorage.py", line 67, in _connect
    self._ssh.connect(self._host, **self._params)
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/paramiko/client.py", line 399, in connect
    our_server_keys = self._host_keys.get(server_hostkey_name)
  File "/usr/lib/python3.7/_collections_abc.py", line 660, in get
    return self[key]
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/paramiko/hostkeys.py", line 245, in __getitem__
    ret = self.lookup(key)
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/paramiko/hostkeys.py", line 191, in lookup
    if self._hostname_matches(hostname, e):
  File "/home/django/manhanah/.manhanah/lib/python3.7/site-packages/paramiko/hostkeys.py", line 207, in _hostname_matches
    and not hostname.startswith("|1|")
AttributeError: 'NoneType' object has no attribute 'startswith'
```

The `django-storages` cofiguration in settings.py:

```
STATICFILES_STORAGE = 'manhanah.core.storage.STATICSFTPStorage'

SFTP_STORAGE_HOST = config('SFTP_STORAGE_HOST')
SFTP_STORAGE_ROOT = config('SFTP_STORAGE_ROOT')
SFTP_STORAGE_PARAMS = {
    'username': config('SFTP_STORAGE_USER'),
    'password': config('SFTP_STORAGE_PASSWORD'),
}
SFTP_STORAGE_INTERACTIVE = config('SFTP_STORAGE_INTERACTIVE', default=False, cast=bool)
```

**Comment by pyprism** [comment]
@rennanflima did you found any solution for this ?

**Comment by jschneier** [comment]
It must be the case that `_host is None`, would need more info.
